version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile
    ports:
      - "8080:8080"

      #in order to make multiple containers run together using a single YAML config file we can use docker compose up. 